services:
  server:
    build: .
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:0.0.0.0"
    networks:
      - server_network
    ports:
      - '8080:8080'
    volumes:
      - ./data:/data


networks:
  server_network:
    driver: bridge

