# Generated by Django 5.1.3 on 2024-11-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Todo'), (1, 'In Process'), (2, 'Done')], default=0)),
                ('end_date', models.DateTimeField(null=True)),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.projectmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.usermodel')),
            ],
        ),
    ]
