# Generated by Django 5.1.3 on 2024-12-17 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_alter_membershipmodel_id_alter_projectmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalRecordModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.IntegerField(choices=[(0, 'Assign Task To User'), (1, 'Unassign Task From User'), (2, 'Set In Process'), (3, 'Set Done'), (4, 'Set Todo'), (5, 'Add User To Project'), (6, 'Promote User In Project')])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.usermodel')),
            ],
        ),
    ]
