# Generated by Django 5.1.3 on 2024-12-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_journalrecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecordmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.projectmodel'),
        ),
        migrations.AlterField(
            model_name='journalrecordmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskmodel'),
        ),
        migrations.AlterField(
            model_name='journalrecordmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.usermodel'),
        ),
    ]
