# Generated by Django 5.1.3 on 2024-12-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_journalrecordmodel_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrecordmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectsapp.projectmodel'),
        ),
        migrations.AlterField(
            model_name='journalrecordmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectsapp.taskmodel'),
        ),
        migrations.AlterField(
            model_name='journalrecordmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectsapp.usermodel'),
        ),
    ]
