# Generated by Django 5.1.3 on 2024-12-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_alter_journalrecordmodel_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
