# Generated by Django 5.1.3 on 2025-05-09 10:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0006_taskmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='TaskBlockModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_timestamp', models.DateTimeField(auto_now_add=True)),
                ('blocked_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='projectsapp.taskmodel')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projectsapp.taskmodel')),
            ],
        ),
    ]
