# Generated by Django 5.1.3 on 2025-05-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0007_alter_taskmodel_description_taskblockmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskblockmodel',
            old_name='blocked_by_id',
            new_name='blocked_by',
        ),
        migrations.RenameField(
            model_name='taskblockmodel',
            old_name='task_id',
            new_name='task',
        ),
    ]
