# Generated by Django 5.1.3 on 2025-05-09 13:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0008_rename_blocked_by_id_taskblockmodel_blocked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependencyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_timestamp', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='projectsapp.taskmodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projectsapp.taskmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskBlockModel',
        ),
    ]
