# Generated by Django 5.1.3 on 2025-05-29 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0009_taskdependencymodel_delete_taskblockmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategoryAssignmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskmodel')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskCategoryAssignmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.taskcategorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsapp.usermodel')),
            ],
        ),
    ]
