# Generated by Django 5.1.3 on 2025-05-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0013_remove_usermodel_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
