# Generated by Django 5.1.3 on 2025-05-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0015_usermodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
    ]
